config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  resources :challenges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'challenges#index'
  get '/challenges/upvote/:id/', to: "challenges#upvote", as: "upvote"
  get '/challenges/collaborate/:id', to: "challenges#collaborate", as: "collaborate"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    validates :title, :description, :tags, presence: true
    belongs_to :employee
    has_many :upvote
    has_many :collaborate
end

app/models/collaborate.rb
class Collaborate < ApplicationRecord
  belongs_to :challenge
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  attr_accessor :login
  has_many :challenge
  has_many :upvote
  has_many :collaborate
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ["lower(emp_id) = :value OR lower(email) = :value",
      { value: login.strip.downcase}]).first
  end
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :employee
  belongs_to :challenge
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_employee!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:emp_id, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
        keys: [:emp_id, :email, :password_confirmation, :current_password])
    end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy upvote collaborate]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.order(params[:sort])
    @challenge = Challenge.new
  end

  # GET /challenges/1 or /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    
    respond_to do |format|
      if @challenge.save
        flash[:notice] = "Challenge was successfully created!!"
        format.html { redirect_to controller: 'challenges', action: 'index'}
        format.json { render :show, status: :created, location: @challenge }
      else
        flash[:alert] = "Can't create empty challenge"
        format.html { redirect_to controller: 'challenges', action: 'index' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # upvote a challenge
  def upvote
    if @challenge.employee_id != current_employee.id
      @validate = Upvote.where({employee_id: current_employee.id, challenge_id: @challenge.id})
      if @validate.blank?  
        @vote = Upvote.new({:employee_id => current_employee.id, :challenge_id => @challenge.id})
        @vote.save
        @challenge.increment!(:votes)
        flash[:notice] = "Challenge upvoted"
      else
        flash[:alert] = "Already upvoted"
      end
    else
      flash[:alert] = "Can't upvote own challenge"
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  # make employee a collaborator
  def collaborate
    if @challenge.employee_id != current_employee.id
      @check_exist = Collaborate.where({challenge_id: @challenge.id, employee_id: current_employee.id})
      if @check_exist.blank?
        @collaborate = Collaborate.new({:challenge_id => @challenge.id, :employee_id => current_employee.id, :emp_id => current_employee.emp_id})
        @collaborate.save
        flash[:notice] = "Congrats, You are collaborator now!"
      else
        flash[:alert] = "Already a collaborator"
      end
    else
      flash[:alert] = "Can't collaborate own challenge"
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:title, :description, :tags, :employee_id, :created_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true) do |form| %>
  <% if challenge.errors.any? %>
    <div class="alert alert-danger">
      <% challenge.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="form-row my-4">
    <div class="col">
      <%= form.text_field :title, id: :challenge_title, placeholder: "Title", class: "form-control" %>
    </div>

    <div class="col-7">
      <%= form.text_area :description, id: :challenge_description,placeholder: "Description",  class: "form-control", rows: "1" %>
    </div>

    <div class="col">
      <%= form.select(:tags, %w[Bit-Manipulation Greedy NumberTheory Searching Sorting String Trees Others], {:prompt => "-Select tag-"}, { :class => "custom-select mb-3"})%>
    </div>

    <%# Hidden fields of the form %>
    <% form.label :employee_id %>
    <%= form.number_field :employee_id, value: current_employee.id, type: :hidden %>

    <% form.label :created_by %>
    <%= form.number_field :created_by, value: current_employee.emp_id, type: :hidden %> 

    <div class="col">
      <%= form.submit "Add Challenge", class: "btn btn-outline-primary"%>
    </div>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<% content_for :title do %>
    <h1 class="text-primary text-center">Challenges</h1>
<% end %>
<hr>
<%#= link_to 'Add New Challenge', new_challenge_path , class: "btn btn-outline-primary my-4" %>
<%= render "challenges/form", challenge: @challenge %>
<hr>

<div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">
          Challenge Id
          <%= link_to :sort => "id" do %>
            <i class="fas fa-sort-numeric-down"></i>
          <% end %>
        </th>
        <th scope="col">
          Title
          <%= link_to :sort => "title" do %>
            <i class="fas fa-sort-alpha-down"></i>
          <% end %>
        </th>
        <th scope="col">Description</th>
        <th scope="col" colspan="2">
          Vote Count
          <%= link_to :sort => "votes" do %>
            <i class="fas fa-sort-numeric-down"></i>
          <% end %>
        </th>
        <th scope="col">Created By</th>
        <th scope="col">
          Created at
          <%= link_to :sort => "created_at" do %>
            <i class="fas fa-sort-numeric-down"></i>
          <% end %>
        </th>
        <th scope="col">Tags</th>
        <th scope="col" colspan="2">Collaborators</th>
      </tr>
    </thead>
    <tbody>
      <% @challenges.each do |challenge| %>
        <tr>
          <td><%= challenge.id %></td>
          <td><%= challenge.title %></td>
          <td><%= challenge.description %></td>
          <td>
            <%= challenge.votes%>
          </td>
          <td>
            <% if challenge.employee_id != current_employee.id %>
              <%= link_to upvote_path(challenge) do %>
                <i class="fas fa-vote-yea"></i> 
              <% end %> 
            <% else %>
              <i class="fas fa-vote-yea text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= challenge.created_by %>
          </td>
          <td><%= challenge.created_at %></td>
          <td><%= challenge.tags %></td>  
          <td>
            <% @collaborators =  Collaborate.where(challenge_id: challenge.id) %>
            <% if !@collaborators.blank?  %>
              <% @collaborators.each do | collaborator | %>
                <%= collaborator.emp_id %>
                <% " " %>
              <% end %>
            <% end %>

          </td>
          <td>
            <% if challenge.employee_id != current_employee.id %>
              <%= link_to collaborate_path(challenge) do %>
                <i class="far fa-check-circle"></i>
              <% end %> 
            <% else %>
              <i class="far fa-check-circle text-muted"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/challenges/new.html.erb
<h1>Add New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @challenge.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @challenge.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @challenge.tags %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>HackFest</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"crossorigin="anonymous">
    
  </head>
  
  <body>
    <%= render partial: "shared/navbar"  %>
    <div class="container-fluid">
      <%= render partial: "shared/alert"  %>
      <%= yield :title %>
      <%= yield %>
    </div>
    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible my-2">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
    </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible mt-2">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
        <p>© copyright 2021 HackFest <br>
    All rights are reserved <br>
    Created by Parth A.</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
    </div>
            <%#= link_to "Sign Up", new_employee_registration_path, class: "btn btn-outline-warning" %>
            <%# <%= link_to "Log In", new_employee_session_path, class: "btn btn-outline-success" %>
            <%= link_to "HackFest", root_path, class: "navbar-brand mx-auto" %>
            <% if employee_signed_in?  %>
                <%= link_to destroy_employee_session_path, class: "btn btn-outline-warning", method: :delete do %>
                    Log Out (<%= current_employee.emp_id %>)
                 <% end %>
            <% end %>
    </div>
    
</nav>